AWSTemplateFormatVersion: '2010-09-09'
Description: "Core Infrastructre for a something something"
Parameters:
  WebBucketName:
    Description: "Name of the bucket hosting the react app"
    Type: String
    Default: "somethingsomething-web-bucket"
  RootDomainName:
    Description: "Don't forget to attach SSL cert manually!"
    Type: String
Resources:
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Sid: PublicReadForGetBucketObjects
          Principal:
            AWS:
              - !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudfrontIdentity}"
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebBucket', /*]]
  WebBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${WebBucketName}"
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "Authorization"
          AllowedMethods:
          - "GET"
          AllowedOrigins:
          - "*"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
  CloudfrontPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "CloudfrontPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - !Sub "arn:aws:s3:::${WebBucketName}/contents/*"
  CloudfrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Used to access S3 Web bucket"
  CloudfrontDistribution:
    DependsOn:
    - WebBucket
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Sub "*.${RootDomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: false
          MaxTTL: 86400
          MinTTL: 0
          TargetOriginId: !Ref WebBucket
          ViewerProtocolPolicy : "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: "http2"
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt WebBucket.DomainName
            Id: !Ref WebBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudfrontIdentity}"
        PriceClass: "PriceClass_All"
